'use strict';

module.exports = {
  'adjoining-classes': true,
  'box-model': false,
  'box-sizing': false,
  'bulletproof-font-face': false,
  'compatible-vendor-prefixes': false,
  'display-property-grouping': true,
  'duplicate-background-images': true,
  'duplicate-properties': true,
  'empty-rules': true,
  'fallback-colors': false,
  'floats': false,
  'font-faces': true,
  'font-sizes': true,
  'gradients': false,
  'ids': false,
  'import': true,
  'important': true,
  'known-properties': false,
  'non-link-hover': false,
  'outline-none': true,
  'overqualified-elements': true,
  'qualified-headings': false,
  'regex-selectors': true,
  'shorthand': true,
  'star-property-hack': true,
  'text-indent': true,
  'underscore-property-hack': true,
  'vendor-prefix': true,
  'unique-headings': false,
  'universal-selector': true,
  'unqualified-attributes': true,
  'zero-units': true,
};
