'use strict';

module.exports = {
  rules: {
    'color-hex-case': 'upper',
    'color-named': 'never',
    'color-no-invalid-hex': true,
    'function-calc-no-unspaced-operator': true,
    'function-max-empty-lines': 1,
    'string-quotes': 'double',
    'string-no-newline': true,
    'unit-case': 'lower',
    'unit-no-unknown': true,
    'value-keyword-case': 'lower',
    'value-list-max-empty-lines': 0,
    'custom-property-empty-line-before': 'never',
    'property-case': 'lower',
    'property-no-unknown': true,
    'declaration-colon-space-before': 'never',
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-ignored-properties': true,
    'declaration-block-no-redundant-longhand-properties': true,
    'declaration-block-trailing-semicolon': 'always',
    'block-closing-brace-empty-line-before': 'never',
    'block-opening-brace-newline-after': 'always',
    'block-no-empty': true,
    'selector-attribute-brackets-space-inside': 'never',
    'selector-descendant-combinator-no-non-space': true,
    'selector-pseudo-class-case': 'lower',
    'selector-pseudo-element-case': 'lower',
    'selector-type-case': 'lower',
    'selector-max-empty-lines': 0,
    'selector-no-universal': true,
    'max-empty-lines': 1,
    'max-line-length': 80,
    'max-nesting-depth': 2,
    'no-eol-whitespace': true,
    'no-extra-semicolons': true,
    'no-invalid-double-slash-comments': true,
    'number-leading-zero': 'always',
    'number-max-precision': 2,
    'number-no-trailing-zeros': true,
    'no-duplicate-selectors': true,
    'font-family-no-duplicate-names': true,
    'font-family-name-quotes': 'always-where-required',
    'length-zero-no-unit': true,
  },
};
